In [2]:
## Question 1
name = "Subham Banerjee"
age = 21

print("My name is", name)
print("I am", age, "years old.")

My name is Subham Banerjee
I am 21 years old.


In [3]:
## Question 2 
X = "Datascience is used to extract meaningful insights."
splitted_string = X.split()

print(splitted_string)

['Datascience', 'is', 'used', 'to', 'extract', 'meaningful', 'insights.']


In [6]:
# Question 3 
def mul(a,b):
    print(a*b)

a = int(input())
b = int(input())
print(a,b)
mul(a,b)

5
6
5 6
30


In [7]:
#Question 4 
states_capitals = {
    "West Bengal": "Kolkata",
    "Assam": "Dispur",
    "Bihar": "Patna",
    "Orissa": "Bhubaneswar ",
    "Punjab": "Chandigarh "
}

# Print the keys
print("Keys:")
for state in states_capitals.keys():
    print(state)

# Print the values
print("Values:")
for capital in states_capitals.values():
    print(capital)


Keys:
West Bengal
Assam
Bihar
Orissa
Punjab
Values:
Kolkata
Dispur
Patna
Bhubaneswar 
Chandigarh 


In [9]:
 # Question 5 
numbers = list(range(1, 1001))


In [10]:
# Question 6 
n = 4  

identity_matrix = []

for i in range(n):
    row = []
    for j in range(n):
        if i == j:
            row.append(1)
        else:
            row.append(0)
    identity_matrix.append(row)

for row in identity_matrix:
    print(row)


[1, 0, 0, 0]
[0, 1, 0, 0]
[0, 0, 1, 0]
[0, 0, 0, 1]


In [11]:
# Question 7 
matrix = []
value = 1

# Populate the matrix with values ranging from 1 to 9
for i in range(3):
    row = []
    for j in range(3):
        row.append(value)
        value += 1
    matrix.append(row)

# Print the matrix
for row in matrix:
    print(row)


[1, 2, 3]
[4, 5, 6]
[7, 8, 9]


In [13]:
#Question 8 
import numpy as np

array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array2 = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])

# Perform element-wise addition
result = array1 + array2

# Print the result
print(result)



[[11 13 15]
 [17 19 21]
 [23 25 27]]


In [14]:
#Question 9

from datetime import datetime, timedelta

start_date = datetime(2023, 2, 1)
end_date = datetime(2023, 3, 1)

current_date = start_date
while current_date <= end_date:
    print(current_date.strftime("%Y-%m-%d"))
    current_date += timedelta(days=1)


2023-02-01
2023-02-02
2023-02-03
2023-02-04
2023-02-05
2023-02-06
2023-02-07
2023-02-08
2023-02-09
2023-02-10
2023-02-11
2023-02-12
2023-02-13
2023-02-14
2023-02-15
2023-02-16
2023-02-17
2023-02-18
2023-02-19
2023-02-20
2023-02-21
2023-02-22
2023-02-23
2023-02-24
2023-02-25
2023-02-26
2023-02-27
2023-02-28
2023-03-01


In [15]:
# Question 10 
import pandas as pd

dictionary = {'Brand': ['Maruti', 'Renault', 'Hyundai'], 'Sales': [250, 200, 240]}

df = pd.DataFrame(dictionary)

print(df)


     Brand  Sales
0   Maruti    250
1  Renault    200
2  Hyundai    240
